### ISSUE TITLE
`guided_tour.rs` in master does not compile with rlua 0.15.3

### ISSUE THREAD

**Issue by kud1ing** [kyren/rlua#110]
Since https://github.com/kyren/rlua/commit/4e4d65efa22a1b89c135abe74b77107cb361668a `guided_tour.rs` uses `context()` which is not available in rlua 0.15.3:

    error[E0599]: no method named `context` found for type `rlua::lua::Lua` in the current scope 

As a newcomer to rlua this puzzled me a bit.

I see the following options for improvement:
* release a rlua > 0.15.3 which works for the `guided_tour.rs` in master
* point out the current situation in the `README.md`
* point to the last revision of `guided_tour.rs` working with rlua 0.15.3

**Comment by kyren** [comment]
Hopefully I will release a 0.16 very soon which will fix this

**Comment by vojtechkral** [comment]
My (amateurish) understanding is that you can just omit the context calls and use the `Lua` object directly.

Fingers crossed for 0.16 :)

**Comment by kyren** [comment]
This is now fixed (0.16 is released 🎉), but there's still the general problem of the examples folder being mismatched in some way with github / external dependencies.  Leaving #91 open for both of these issues.

**Comment by kud1ing** [comment]
Nice thank you.
